eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8761/eureka/,http://eureka1:8762/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka3
spring:
  application:
    name: eureka
server:
  port: 8763