eureka:
  client:
    service-url:
      defaultZone: http://eureka2:8762/eureka/,http://eureka3:8763/eureka/
    register-with-eureka: true
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka1
spring:
  application:
    name: eureka
server:
  port: 8761
