chander: I'am not chander,too asfasd
spring:
  application:
    name: Employee
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  messages:
    basename: i18n.login
  rabbitmq:
    host: 172.25.154.161
    port: 5672
    username: guest
    password: guest
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
