chander: chenchuan 34324 hello adsfasd
spring:
  rabbitmq:
    #host: 172.25.154.161
    host: 221.232.143.222
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
  messages:
    basename: i18n.login
server:
#  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /
